# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e508d1245687e87ca047fd89d2303848305d1cca1ab0bc69e5602f50d151ee31cb4d61a4a23285f2c270e3b57dc7b165b0f35fbb2276e971cce112b3c245198f

test:
  secret_key_base: f25c7e0661dc80d07dc45d982cf0d332f0947f64a8bf020675e4f603c28527ca535754722d4b2ee50ca9ec8ba98f52e49cae61eb75d42cf286b969b8073e4732

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
